# Generated by Django 4.2.3 on 2023-11-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0082_alter_mensajeuser_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeuser',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=1537),
            preserve_default=False,
        ),
    ]
