# Generated by Django 4.2.3 on 2023-11-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0083_mensajeuser_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeuser',
            name='hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
