# Generated by Django 4.2.3 on 2023-11-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0084_alter_mensajeuser_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeuser',
            name='hora',
        ),
    ]
